'use client'
import { Download } from "lucide-react";
import { Button } from "../ui/button";

export default function DownloadSummaryButton({
  title,
  summaryText,
  fileName,
  createdAt,
}:{
    title: string;
    summaryText: string;
    fileName: string;
    createdAt: string;

}

) {
    const handleDwnload=()=>{
const summaryContent =`
# ${title}
Generated Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}
        
${summaryText}
        
Original File: ${fileName}
GEnerated by Sommaire
        `;

        const blob = new Blob([summaryContent], {
            type:'text/plain'
        })
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Summary-${title.replace(/[^a-z0-9]/gi,'_')}.txt`;
        a.click();
    
    }
  return <Button size='sm'
  className="h-8 px-3 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-50"
  onClick={handleDwnload}>
    <Download className="h-4 w-4 mr-1"/>Download Summary</Button>;
}
